name: goliaths
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  country_list:
    git:
      url: https://github.com/khsuzan/country_list.git
  lunary:
    path: ./lunary
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  flutter_otp_text_field: ^1.5.1+1
  awesome_calendart: ^1.2.1
  http:
  shared_preferences: ^2.5.3
  table_calendar: ^3.0.9
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poly
      fonts:
        - asset: assets/fonts/Poly-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poly-Italic.ttf
          weight: 400
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Rakkas
      fonts:
        - asset: assets/fonts/Rakkas-Regular.ttf
          weight: 400
